### ISSUE TITLE
Pragma "Warnings" does not permit identifier "Reason" here

### ISSUE THREAD

**Issue by knyberg** [samueltardieu/adasockets#1]
At lines 319 and 341 of sockets.adb in version 1.9.  Tested with gcc 4.6.3, 4.8.2, on ubuntu 12.04 and 14.04 on Intel hardware.

**Comment by samueltardieu** [comment]
Indeed, this has been fixed in cf3469668f6cec8b72591f0f3ce4550330c0997a but the fixed version had not been released.

I have just released 1.9.1 with this fix, you can get it from https://github.com/samueltardieu/adasockets/releases/tag/v1.9.1

Thanks for the report.
