### ISSUE TITLE
(WishList) IPv6 support.

### ISSUE THREAD

**Issue by danieagle** [samueltardieu/adasockets#10]
Hi!

Please add support for IPv6 with bind() for ipv6 too.

Thanks !
Best wishes, Daniel.

**Comment by samueltardieu** [comment]
I won't add it myself as I don't need it, but I welcome pull requests if someone wishes to have their implementation integrated.

**Comment by danieagle** [comment]
Thanks!

Which Ada Version do you prefer?

Very Very Thanks!
Best wishes, Daniel.
