### ISSUE TITLE
Multicast socket initialization is not correct, prevents multicast datagrams to be received

### ISSUE THREAD

**Issue by guifo** [samueltardieu/adasockets#5]
For an application to received multicast datagrams, the way adasockets initializes a multicast socket shall be modified so the bind operation is done using 0.0.0.0 while add_membership refers to the IP address of the actual interface used to transport the multicast traffic..

**Comment by guifo** [comment]
I have sent a pull request but the Travis jobs hangs with

././adasockets.texi:301: I can't find file `sockets.texi'.

It seems this is not related to my changes.

**Comment by samueltardieu** [comment]
Yes, this is unrelated to your changes indeed. I'll have a look at your pull-request as soon as possible.

**Comment by samueltardieu** [comment]
Fixed by #6. Thanks for your contribution! I will issue a new AdaSockets release.
